#listener_test:
#  class:      Demo\Demo\EventListeners\TestListener
#  method:     methode_test
#  event:      pegase.core.event:pre_call
#  parameters: ~

form_listener_init:
  class:      Pegase\Security\Form\EventListeners\FormListener
  method:     load_tokens
  event:      application.loaded
  parameters: ~

form_listener_end:
  class:      Pegase\Security\Form\EventListeners\FormListener
  method:     save_tokens
  event:      application.end
  parameters: ~

