#listener_test:
#  class:      Demo\Demo\EventListeners\TestListener
#  method:     methode_test
#  event:      pegase.core.event:pre_call
#  parameters: ~

pegase_listeners:
  import:
    module: Pegase
    file: Config/event_listeners.yml


